name: Code Quality Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: npm install
        
      - name: Prisma Generate
        # We "inject" a temporary variable just for this step
        run: npx prisma generate 
        env:
          DATABASE_URL: "file:./temp.db" 

      - name: Check Types
        run: npx tsc --noEmit
        env:
          DATABASE_URL: "file:./temp.db"

      - name: Build Project
        run: npm run build
        env:
          DATABASE_URL: "file:./temp.db"